Using the typing dataset from that was label encoded duing preprocessing

In [9]:
#Importing dependencies and modules

import pandas as pd
import sklearn 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [10]:
df = pd.read_csv("/users/imbahndu/Desktop/Columbia DBM/Typing dataset/lightbgm.csv")

In [11]:
df

,Unnamed: 0,Hand,HoldTime,Direction,LatencyTime,FlightTime,Parkinsons,Gender_Male
0,0,0,101.6,0,234.4,156.3,True,False
1,1,0,85.9,0,437.5,359.4,True,False
2,2,0,78.1,0,210.9,125.0,True,False
3,3,0,62.5,0,359.4,281.3,True,False
4,6,1,85.9,1,195.3,117.2,True,False
...,...,...,...,...,...,...,...,...
6236971,9316853,0,195.3,2,425.8,261.7,True,False
6236972,9316854,1,105.5,1,214.8,19.5,True,False
6236973,9316855,0,168.0,0,332.0,15.6,True,False
6236974,9316856,0,97.7,0,281.3,113.3,True,False
6236975,9316857,0,168.0,0,160.2,62.5,True,False

In [12]:
#Dropping the unmaned column right away
df.drop(columns= "Unnamed: 0")

,Hand,HoldTime,Direction,LatencyTime,FlightTime,Parkinsons,Gender_Male
0,0,101.6,0,234.4,156.3,True,False
1,0,85.9,0,437.5,359.4,True,False
2,0,78.1,0,210.9,125.0,True,False
3,0,62.5,0,359.4,281.3,True,False
4,1,85.9,1,195.3,117.2,True,False
...,...,...,...,...,...,...,...
6236971,0,195.3,2,425.8,261.7,True,False
6236972,1,105.5,1,214.8,19.5,True,False
6236973,0,168.0,0,332.0,15.6,True,False
6236974,0,97.7,0,281.3,113.3,True,False
6236975,0,168.0,0,160.2,62.5,True,False

In [16]:
df["Parkinsons"].value_counts()

Parkinsons
True     4484045
False    1752931
Name: count, dtype: int64

In [ ]:
#Importing modules
from sklearn.model_selection import train_test_split
import lightgbm

In [14]:
#Defining the features and labels for dataset 
y = df["Parkinsons"]

X = df.drop(columns=["Parkinsons", "Gender_Male"])

In [ ]:
X_test